# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-gist
- jekyll-twitter-plugin

# Site settings
url: 'https://psychblog.berkeley.edu/'
baseurl: ''
title: 'Berkeley Psychology Graduate Blog'
description: 'Berkeley Psychology Graduate Blog'
permalink: pretty
logo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Greek_uc_psi.svg"
email: "maedbhking@berkeley.edu"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: News
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
# - title: Outreach
#   url: /outreach/
# - title: Opinion
#   url: /opinion/
- title: Categories
  url: /categories/
- title: Contact
  url: /contact/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Shining a Light on Graduate Student Research
    output: true
    description: "Each month we publish opinion pieces and interviews with psychology graduate students, across 
    all areas of psychology: cognitive and behavioural neuroscience, social-personality, cognition, and development."
    feature_text: |
      <font color="white" size="8pt">Spotlights and Opinions</font>
    feature_image: "/images/Blog_Spotlights_Cover.jpg"
